import Head from 'next/head'
import { useState, useEffect } from 'react';
import Card from './../../types/Card';

export default function Home() {

  const [allCards, setAllCards] = useState <Card[]>([])

  const url = "http://localhost:3000/cards";

  async function getCards(): Promise<void> {
    try {
      const res = await fetch(url);
      const data = await res.json();
      setAllCards(data);
    } catch (err) {
      throw { message: { err } };
    }
  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="test">
        <p>Test</p>
        <button onClick={() => getCards()}>Fetch</button>
        <p></p>
      </div>
      </main>
    </>
  )
}
